theme: jekyll-theme-cayman
title: Welcome!
description: All the tutorials I found were in parts, and weren't simply explained. This is for future reference to myself, or anyone else starting their own bots on Discord.
